version: '3'
services:
    ebot-web:
        restart: always
        image: gymitpro/ebot-web:v1.0
        environment:
            - DATABASE_EXISTS
            - EBOT_ADMIN_LOGIN
            - EBOT_ADMIN_PASSWORD
            - EBOT_ADMIN_EMAIL
            - MYSQL_DATABASE
            - MYSQL_ROOT_PASSWORD
        volumes:
            - "eBotWebVolume:/app/eBot-CSGO-Web"
            - "./ebot-logs:/app/ebot-logs"
            - "./ebot-demos:/app/ebot-demos"
            - "./etc/eBotWeb/app_user.yml:/app/eBot-CSGO-Web/config/app_user.yml"
            - "./etc/eBotWeb/databases.yml:/app/eBot-CSGO-Web/config/databases.yml"
        links:
            - mysqldb
        depends_on:
            - mysqldb
    ebot-socket:
        restart: always
        image: gymitpro/ebot-socket:v1.0
        ports:
            - "12360:12360"
        volumes:
            - "./ebot-logs:/app/eBot-CSGO/logs"
            - "./ebot-demos:/app/eBot-CSGO/demos"
            - "./etc/eBotSocket/config.ini:/app/eBot-CSGO/config/config.ini"
        links:
            - mysqldb
            - redis
        depends_on:
            - mysqldb
            - ebot-web
            - redis
    ebot-logs-receiver:
        restart: always
        image: gymitpro/ebot-logs-receiver:v1.0
        ports:
            - "12345:12345"
        volumes:
            - "./etc/eBotLogReceiver/config.json:/app/ebot-project/configs/config.json"
        links:
            - redis
        depends_on:
            - redis
    mysqldb:
        image: biarms/mysql:5.7
        restart: always
        environment:
            - MYSQL_DATABASE
            - MYSQL_ROOT_PASSWORD
            - MYSQL_USER
            - MYSQL_PASSWORD
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
    redis:
        image: redis:alpine
        restart: always
        volumes:
            - ./data/redis:/data
    nginx:
        image: nginx:alpine
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "eBotWebVolume:/app/eBot-CSGO-Web"
        ports:
            - "80:80"
            - "443:443"
        restart: always
        links:
            - ebot-web
            - ebot-socket
        depends_on:
            - ebot-web
            - mysqldb
volumes:
  eBotWebVolume:
